In [1]:
import torch

** Tensors **

Tensors are similar to numpy arrays, with addition power to use gpu.

Construct a 5x5 matrix, uninitialized.

Note: This matrix takes the garbage value from the location it is declare.

In [2]:
x = torch.empty(5, 5)
print(x)

tensor([[3.1886e-12, 6.8608e+22, 1.1446e+24, 2.0194e-19, 5.0833e+31],
        [1.8936e+23, 7.7447e+31, 1.6929e+22, 2.9514e+29, 1.2124e+25],
        [7.1463e+22, 1.8759e+28, 8.3967e-33, 1.3563e-19, 6.7713e+22],
        [4.5145e+27, 9.4979e+23, 7.1554e+22, 2.7523e+23, 1.6556e+22],
        [7.9452e+08, 6.6129e+19, 6.6532e-33, 4.3612e+27, 8.7518e-04]])


Construct randomly initialized matrix.

In [3]:
x = torch.rand(5, 5)
print(x)

tensor([[0.0966, 0.0072, 0.6108, 0.7094, 0.5697],
        [0.5500, 0.7075, 0.8456, 0.4299, 0.8779],
        [0.6861, 0.8931, 0.7038, 0.4765, 0.1129],
        [0.8052, 0.9176, 0.9454, 0.7136, 0.9218],
        [0.3281, 0.3408, 0.6152, 0.4023, 0.8072]])


Contruct a matrix filled with zeros.

In [4]:
x = torch.zeros(5,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


Contruct a matrix directly from data.

In [5]:
x = torch.tensor([1, 2, 3, 4, 5])
print(x)

tensor([1, 2, 3, 4, 5])


Contructing tensors from existing tensors of different sizes and dtypes.(Unless user gives new values)

In [6]:
x = x.new_ones(5, 3, dtype=torch.double) # new_* takes in sizes.
print(x)

x = torch.rand_like(x, dtype=torch.float) # *_like takes in tensors.
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.4137, 0.0035, 0.0069],
        [0.4101, 0.0291, 0.4463],
        [0.3941, 0.2608, 0.2843],
        [0.6220, 0.2708, 0.1960],
        [0.3741, 0.4757, 0.6725]])


Get tensor size or shape.
They give same result.

Note: torch.Size is a tuple.

In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


** Operations **

There are multiple syntax for operations.
We look at addition operation.

Addition: Syntax 1

In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.8363, 0.2577, 0.8956],
        [0.7609, 0.0645, 0.6072],
        [0.5371, 0.8923, 0.3786],
        [1.3941, 1.1907, 0.6137],
        [0.8105, 0.6989, 1.3978]])


Addition: Syntax 2

In [9]:
print(torch.add(x, y))

tensor([[0.8363, 0.2577, 0.8956],
        [0.7609, 0.0645, 0.6072],
        [0.5371, 0.8923, 0.3786],
        [1.3941, 1.1907, 0.6137],
        [0.8105, 0.6989, 1.3978]])


Addition: Providing an output tensor as agrument.

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.8363, 0.2577, 0.8956],
        [0.7609, 0.0645, 0.6072],
        [0.5371, 0.8923, 0.3786],
        [1.3941, 1.1907, 0.6137],
        [0.8105, 0.6989, 1.3978]])


Addition: in-place.

In [11]:
y.add_(x) # Adds x to y.

tensor([[0.8363, 0.2577, 0.8956],
        [0.7609, 0.0645, 0.6072],
        [0.5371, 0.8923, 0.3786],
        [1.3941, 1.1907, 0.6137],
        [0.8105, 0.6989, 1.3978]])

Note: Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

You can use all Numpy-Like indexing.

In [12]:
print(x[:, 1]) # It gives column 1.

tensor([0.0035, 0.0291, 0.2608, 0.2708, 0.4757])


Resizing: If you want to resize or reshape your tensors use .view().

In [13]:
x = torch.rand(4, 4)
y = x.view(16) # It should be multiple.
z = x.view(-1, 8) # -1 inferred for other dimensions.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


Get Python number from one value tensor.

In [14]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6121])
-0.6120971441268921


** Numpy Bridge **

Converting Torch Tensors to Numpy array and vice-versa.

Note: The Torch Tensors and Numpy array share same location(On CPU) if converted. So, changing one will change other.

Converting Torch Tensor to Numpy array.

In [15]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


See how changing one changes other.

In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting Numpy array to Torch Tensor.

In [17]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


See changing Numpy array changes Torch Tensor.

In [18]:
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Note: All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

See more on https://pytorch.org/docs/stable/torch.html